max_connections = 200
shared_buffers = 128MB  
work_mem = 16MB
maintenance_work_mem = 256MB
# default
#listen_addresses = 'localhost'
#port = 5432
# -- Logging --
#log_destination = 'stderr'
#logging_collector = off
#log_rotation_age = 1d
#log_rotation_size = 10MB
#log_truncate_on_rotation = off
